services:
  http11:
    image: mnvkd
    build:
      context: .
    ports:
      - "8080:8080"
    cap_add:
      - SYS_PTRACE
    environment:
      VK_POLL_DRIVER: OS
      VK_POLL_METHOD: EDGE_TRIGGERED
    cpuset: "0"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  http11d:
    image: mnvkd
    build:
      context: .
    command:
      - "/vk_http11.debug"
    ports:
      - "8081:8080"
    cap_add:
      - SYS_PTRACE
    environment:
      VK_POLL_DRIVER: OS
      VK_POLL_METHOD: EDGE_TRIGGERED
    cpuset: "2,4,6"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  httpexpress:
    image: expresshw
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - "8082:3000"
    cpuset: "1"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  httpunit:
    image: unithw
    build:
      context: .
      dockerfile: Dockerfile.unit
    ports:
      - "8083:8080"
    cpuset: "1"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  http11-fortio:
    image: fortio/fortio
    command:
      - "load"
      - "-t=30s"
      - "-c=200"
      - "-qps=0"
      - "http://http11:8081/"
    depends_on:
      http11:
        condition: service_started
    cpuset: "2,4,6"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  http11-test30:
    image: mnvkd-test
    build:
      context: .
      dockerfile: Dockerfile.test
    command:
      - "30"
    depends_on:
      http11-fortio:
        condition: service_completed_successfully
    cpuset: "2,4,6"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  httpexpress-test30:
    image: mnvkd-testexpress
    build:
      context: .
      dockerfile: Dockerfile.test.express
    command:
      - "30"
    depends_on:
      http11-test30:
        condition: service_completed_successfully
    cpuset: "2,4,6"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  httpunit-test30:
    image: mnvkd-testunit
    build:
      context: .
      dockerfile: Dockerfile.test.unit
    command:
      - "30"
    depends_on:
      httpexpress-test30:
        condition: service_completed_successfully
    cpuset: "2,4,6"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  http11-test1k:
    image: mnvkd-test
    command:
      - "1000"
    depends_on:
      httpunit-test30:
        condition: service_completed_successfully
    cpuset: "2,4,6"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  httpexpress-test1k:
    image: mnvkd-testexpress
    command:
      - "1000"
    depends_on:
      http11-test1k:
        condition: service_completed_successfully
    cpuset: "2,4,6"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  httpunit-test1k:
    image: mnvkd-testunit
    command:
      - "1000"
    depends_on:
      httpexpress-test1k:
        condition: service_completed_successfully
    cpuset: "2,4,6"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  http11-test10k:
    image: mnvkd-test
    command:
      - "10000"
    depends_on:
      httpunit-test1k:
        condition: service_completed_successfully
    cpuset: "2,4,6"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  httpexpress-test10k:
    image: mnvkd-testexpress
    command:
      - "10000"
    depends_on:
      http11-test10k:
        condition: service_completed_successfully
    cpuset: "2,4,6"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
  httpunit-test10k:
    image: mnvkd-testunit
    command:
      - "10000"
    depends_on:
      httpexpress-test10k:
        condition: service_completed_successfully
    cpuset: "2,4,6"
    ulimits:
      nofile: 65536
    mem_limit: 4G
    deploy:
      resources:
        limits:
          memory: 4G
