services:
  http11:
    image: mnvkd
    build:
      context: .
    ports:
      - "8080:8080"
    cap_add:
      - SYS_PTRACE
  http11d:
    image: mnvkd
    build:
      context: .
    command:
      - "/vk_http11.debug"
    ports:
      - "8081:8080"
    cap_add:
      - SYS_PTRACE