services:
  http11:
    image: mnvkd
    build:
      context: .
    ports:
      - "8080:8080"
    cap_add:
      - SYS_PTRACE
    environment:
      VK_POLL_DRIVER: OS
      VK_POLL_METHOD: EDGE_TRIGGERED
    cpuset: "0"
  http11d:
    image: mnvkd
    build:
      context: .
    command:
      - "/vk_http11.debug"
    ports:
      - "8081:8080"
    cap_add:
      - SYS_PTRACE
    environment:
      VK_POLL_DRIVER: OS
      VK_POLL_METHOD: EDGE_TRIGGERED
    cpuset: "0"
  http11-test30:
    image: mnvkd-test
    build:
      context: .
      dockerfile: Dockerfile.test
    command:
      - "30"
    depends_on:
      http11:
        condition: service_started
    cpuset: "1"
  http11-test1k:
    image: mnvkd-test
    command:
      - "1000"
    depends_on:
      http11-test30:
        condition: service_completed_successfully
    cpuset: "1"
  http11-test10k:
    image: mnvkd-test
    command:
      - "10000"
    depends_on:
      http11-test1k:
        condition: service_completed_successfully
    cpuset: "1"