services:
  http11:
    image: mnvkd
    build:
      context: .
    ports:
      - "8080:8080"
    cap_add:
      - SYS_PTRACE
    environment:
      VK_POLL_DRIVER: OS
      VK_POLL_METHOD: EDGE_TRIGGERED
  http11d:
    image: mnvkd
    build:
      context: .
    command:
      - "/vk_http11.debug"
    ports:
      - "8081:8080"
    cap_add:
      - SYS_PTRACE
    environment:
      VK_POLL_DRIVER: OS
      VK_POLL_METHOD: EDGE_TRIGGERED
  http11-test:
    image: mnvkd-test
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      http11:
        condition: service_started